[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "forge-cache"

remappings = [
    "@openzeppelin/contracts=node_modules/@openzeppelin/contracts/",
    "OAO/=lib/OAO/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
